---
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "18:00"
      timezone: "America/Los_Angeles"

  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
      time: "18:00"
      timezone: "America/Los_Angeles"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: "America/Los_Angeles"
