title: Vaccinate The States
languages: ["en", "es"]

url: https://vaccinatethestates.com

twitter: vaxthestates

email:
    outreach: outreach@vaccinatethestates.com
    media: media@vaccinatethestates.com
    partners: partners@vaccinatethestates.com
  
google_analytics_id: G-P9ZQGN9BXT

include:
  - _redirects

exclude:
  - netlify.toml
  - package.json
  - package-lock.json
  - CODEOWNERS
  - LICENSE
  - README.md
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - script/
  - webpack/
  - Procfile
  - Procfile.prod
  - postcss.config.js
  - postcss/
  - webpack.common.js
  - webpack.dev.js
  - webpack.prod.js
  - tailwind.config.js
