title: Vaccinate The States
languages: ["en", "es"]

url: https://beta.vaccinatethestates.com

twitter: vaxthestates
instagram: vaccinatethestates

email:
    outreach: outreach@vaccinateca.com

include:
  - _redirects

exclude:
  - netlify.toml
  - package.json
  - package-lock.json
  - CODEOWNERS
  - LICENSE
  - README.md
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - script/
  - webpack/
  - Procfile
  - Procfile.prod
  - postcss.config.js
  - postcss/
  - webpack.common.js
  - webpack.dev.js
  - webpack.prod.js
  - tailwind.config.js