#!/bin/bash
set -e -u

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

bundle install
npm install

if [ $# -ge 1 ] && [ "$1" = "--prod" ]; then
    npx nf start --procfile Procfile.prod
else
    npx nf start
fi
